services:
  alies:
    build:
      context: .
      dockerfile: config/build/Dockerfile
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"
    container_name: alies
    environment:
      - PHP_ENV=production

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx/

  db:
    image: mariadb:latest
    environment:
      # do change these please ! (randomly generated)
      # to security folk : this password isn't used anywhere, I think its better then "password"
      MYSQL_ROOT_PASSWORD: 2jgUdSFWagS7zW2
      MYSQL_DATABASE: alies
      MYSQL_USER: alies_user
      MYSQL_PASSWORD: BO6ZfNW9CK0QGKU
    volumes:
      - db_data:/var/lib/mysql
      # its not working yet
      # - ./config/dump:/docker-entrypoint-initdb.d

volumes:
  db_data:
